### ISSUE TITLE
Work to do with Dasch@Unil

### ISSUE THREAD

**Issue by elespdn** [gustaveroudproject/roud-oeuvres-app#132]
Some work to do between now and August 2021 (40h) !

- [x] demander **espace serveur** au CI
- [x] avoir **app** (master qui parle avec prod) sur ce serveur
- [ ] loading
- [x] afficher les labels d'une **liste** en **français**. Voir https://github.com/gustaveroudproject/roud-oeuvres-app/issues/78
- [ ] revenir en arrière à la **page précédente**, lors qu'on passe à une nouvelle page à travers un lien qui utilise le composant resource-router (qui lit le IRI, fait une requête pour en connaître la classe et adresse le router selon la classe, par exemple s'il s'agit d'une personne on passe de  /resource/IRI  à  /persons/IRI ). Voir https://github.com/gustaveroudproject/roud-oeuvres-app/issues/39. @loicjaouen : solution dans Angular peut-être, mais ça peut être compliqué s'il faut faire cela sut toutes les pages.
- [ ] intégrer dans l'app un **viewer** pour les pages des manuscrits et des publications numérisées (qui inclut feuilleter, zoom, move around, "go to page" menu, "go to chapter" menu, ...) : par exemple, OpenSeadragon ou le viewer de Knora-ui ou autre chose compliant IIIF.     Will check where Knora-ui is in Spring/Summer 2021 and then decide. See details in #212. The viewer is also needed for the data visualizations, see #230.

**Comment by loicjaouen** [comment]
La demande du serveur a été faite au CI (ticket 10414108 2020-12-02), à suivre.
